import { Component } from '@angular/core';

@Component({
  selector: 'app-dropdown',
  templateUrl: './dropdown.component.html',
  styleUrls: ['./dropdown.component.scss']
})
export class SemanticDropdownComponent {
  public value1: number;

  public countries: { value: string, text: string }[] = [
    { value: 'af', text: 'Afghanistan' },
    { value: 'ax', text: 'Aland Islands' },
    { value: 'al', text: 'Albania' },
    { value: 'dz', text: 'Algeria' },
    { value: 'as', text: 'American Samoa' },
    { value: 'ad', text: 'Andorra' },
    { value: 'ao', text: 'Angola' },
    { value: 'ai', text: 'Anguilla' },
    { value: 'ag', text: 'Antigua' },
    { value: 'ar', text: 'Argentina' },
    { value: 'am', text: 'Armenia' },
    { value: 'aw', text: 'Aruba' },
    { value: 'au', text: 'Australia' },
    { value: 'at', text: 'Austria' },
    { value: 'az', text: 'Azerbaijan' },
    { value: 'bs', text: 'Bahamas' },
    { value: 'bh', text: 'Bahrain' },
    { value: 'bd', text: 'Bangladesh' },
    { value: 'bb', text: 'Barbados' },
    { value: 'by', text: 'Belarus' },
    { value: 'be', text: 'Belgium' },
    { value: 'bz', text: 'Belize' },
    { value: 'bj', text: 'Benin' },
    { value: 'bm', text: 'Bermuda' },
    { value: 'bt', text: 'Bhutan' },
    { value: 'bo', text: 'Bolivia' },
    { value: 'ba', text: 'Bosnia' },
    { value: 'bw', text: 'Botswana' },
    { value: 'bv', text: 'Bouvet Island' },
    { value: 'br', text: 'Brazil' },
    { value: 'vg', text: 'British Virgin Islands' },
    { value: 'bn', text: 'Brunei' },
    { value: 'bg', text: 'Bulgaria' },
    { value: 'bf', text: 'Burkina Faso' },
    { value: 'mm', text: 'Burma' },
    { value: 'bi', text: 'Burundi' },
    { value: 'tc', text: 'Caicos Islands' },
    { value: 'kh', text: 'Cambodia' },
    { value: 'cm', text: 'Cameroon' },
    { value: 'ca', text: 'Canada' },
    { value: 'cv', text: 'Cape Verde' },
    { value: 'ky', text: 'Cayman Islands' },
    { value: 'cf', text: 'Central African Republic' },
    { value: 'td', text: 'Chad' },
    { value: 'cl', text: 'Chile' },
    { value: 'cn', text: 'China' },
    { value: 'cx', text: 'Christmas Island' },
    { value: 'cc', text: 'Cocos Islands' },
    { value: 'co', text: 'Colombia' },
    { value: 'km', text: 'Comoros' },
    { value: 'cg', text: 'Congo Brazzaville' },
    { value: 'cd', text: 'Congo' },
    { value: 'ck', text: 'Cook Islands' },
    { value: 'cr', text: 'Costa Rica' },
    { value: 'ci', text: 'Cote Divoire' },
    { value: 'hr', text: 'Croatia' },
    { value: 'cu', text: 'Cuba' },
    { value: 'cy', text: 'Cyprus' },
    { value: 'cz', text: 'Czech Republic' },
    { value: 'dk', text: 'Denmark' },
    { value: 'dj', text: 'Djibouti' },
    { value: 'dm', text: 'Dominica' },
    { value: 'do', text: 'Dominican Republic' },
    { value: 'ec', text: 'Ecuador' },
    { value: 'eg', text: 'Egypt' },
    { value: 'sv', text: 'El Salvador' },
    { value: 'gb', text: 'England' },
    { value: 'gq', text: 'Equatorial Guinea' },
    { value: 'er', text: 'Eritrea' },
    { value: 'ee', text: 'Estonia' },
    { value: 'et', text: 'Ethiopia' },
    { value: 'eu', text: 'European Union' },
    { value: 'fk', text: 'Falkland Islands' },
    { value: 'fo', text: 'Faroe Islands' },
    { value: 'fj', text: 'Fiji' },
    { value: 'fi', text: 'Finland' },
    { value: 'fr', text: 'France' },
    { value: 'gf', text: 'French Guiana' },
    { value: 'pf', text: 'French Polynesia' },
    { value: 'tf', text: 'French Territories' },
    { value: 'ga', text: 'Gabon' },
    { value: 'gm', text: 'Gambia' },
    { value: 'ge', text: 'Georgia' },
    { value: 'de', text: 'Germany' },
    { value: 'gh', text: 'Ghana' },
    { value: 'gi', text: 'Gibraltar' },
    { value: 'gr', text: 'Greece' },
    { value: 'gl', text: 'Greenland' },
    { value: 'gd', text: 'Grenada' },
    { value: 'gp', text: 'Guadeloupe' },
    { value: 'gu', text: 'Guam' },
    { value: 'gt', text: 'Guatemala' },
    { value: 'gw', text: 'Guinea-Bissau' },
    { value: 'gn', text: 'Guinea' },
    { value: 'gy', text: 'Guyana' },
    { value: 'ht', text: 'Haiti' },
    { value: 'hm', text: 'Heard Island' },
    { value: 'hn', text: 'Honduras' },
    { value: 'hk', text: 'Hong Kong' },
    { value: 'hu', text: 'Hungary' },
    { value: 'is', text: 'Iceland' },
    { value: 'in', text: 'India' },
    { value: 'io', text: 'Indian Ocean Territory' },
    { value: 'id', text: 'Indonesia' },
    { value: 'ir', text: 'Iran' },
    { value: 'iq', text: 'Iraq' },
    { value: 'ie', text: 'Ireland' },
    { value: 'il', text: 'Israel' },
    { value: 'it', text: 'Italy' },
    { value: 'jm', text: 'Jamaica' },
    { value: 'jp', text: 'Japan' },
    { value: 'jo', text: 'Jordan' },
    { value: 'kz', text: 'Kazakhstan' },
    { value: 'ke', text: 'Kenya' },
    { value: 'ki', text: 'Kiribati' },
    { value: 'kw', text: 'Kuwait' },
    { value: 'kg', text: 'Kyrgyzstan' },
    { value: 'la', text: 'Laos' },
    { value: 'lv', text: 'Latvia' },
    { value: 'lb', text: 'Lebanon' },
    { value: 'ls', text: 'Lesotho' },
    { value: 'lr', text: 'Liberia' },
    { value: 'ly', text: 'Libya' },
    { value: 'li', text: 'Liechtenstein' },
    { value: 'lt', text: 'Lithuania' },
    { value: 'lu', text: 'Luxembourg' },
    { value: 'mo', text: 'Macau' },
    { value: 'mk', text: 'Macedonia' },
    { value: 'mg', text: 'Madagascar' },
    { value: 'mw', text: 'Malawi' },
    { value: 'my', text: 'Malaysia' },
    { value: 'mv', text: 'Maldives' },
    { value: 'ml', text: 'Mali' },
    { value: 'mt', text: 'Malta' },
    { value: 'mh', text: 'Marshall Islands' },
    { value: 'mq', text: 'Martinique' },
    { value: 'mr', text: 'Mauritania' },
    { value: 'mu', text: 'Mauritius' },
    { value: 'yt', text: 'Mayotte' },
    { value: 'mx', text: 'Mexico' },
    { value: 'fm', text: 'Micronesia' },
    { value: 'md', text: 'Moldova' },
    { value: 'mc', text: 'Monaco' },
    { value: 'mn', text: 'Mongolia' },
    { value: 'me', text: 'Montenegro' },
    { value: 'ms', text: 'Montserrat' },
    { value: 'ma', text: 'Morocco' },
    { value: 'mz', text: 'Mozambique' },
    { value: 'na', text: 'Namibia' },
    { value: 'nr', text: 'Nauru' },
    { value: 'np', text: 'Nepal' },
    { value: 'an', text: 'Netherlands Antilles' },
    { value: 'nl', text: 'Netherlands' },
    { value: 'nc', text: 'New Caledonia' },
    { value: 'pg', text: 'New Guinea' },
    { value: 'nz', text: 'New Zealand' },
    { value: 'ni', text: 'Nicaragua' },
    { value: 'ne', text: 'Niger' },
    { value: 'ng', text: 'Nigeria' },
    { value: 'nu', text: 'Niue' },
    { value: 'nf', text: 'Norfolk Island' },
    { value: 'kp', text: 'North Korea' },
    { value: 'mp', text: 'Northern Mariana Islands' },
    { value: 'no', text: 'Norway' },
    { value: 'om', text: 'Oman' },
    { value: 'pk', text: 'Pakistan' },
    { value: 'pw', text: 'Palau' },
    { value: 'ps', text: 'Palestine' },
    { value: 'pa', text: 'Panama' },
    { value: 'py', text: 'Paraguay' },
    { value: 'pe', text: 'Peru' },
    { value: 'ph', text: 'Philippines' },
    { value: 'pn', text: 'Pitcairn Islands' },
    { value: 'pl', text: 'Poland' },
    { value: 'pt', text: 'Portugal' },
    { value: 'pr', text: 'Puerto Rico' },
    { value: 'qa', text: 'Qatar' },
    { value: 're', text: 'Reunion' },
    { value: 'ro', text: 'Romania' },
    { value: 'ru', text: 'Russia' },
    { value: 'rw', text: 'Rwanda' },
    { value: 'sh', text: 'Saint Helena' },
    { value: 'kn', text: 'Saint Kitts and Nevis' },
    { value: 'lc', text: 'Saint Lucia' },
    { value: 'pm', text: 'Saint Pierre' },
    { value: 'vc', text: 'Saint Vincent' },
    { value: 'ws', text: 'Samoa' },
    { value: 'sm', text: 'San Marino' },
    { value: 'gs', text: 'Sandwich Islands' },
    { value: 'st', text: 'Sao Tome' },
    { value: 'sa', text: 'Saudi Arabia' },
    { value: 'sn', text: 'Senegal' },
    { value: 'cs', text: 'Serbia' },
    { value: 'rs', text: 'Serbia' },
    { value: 'sc', text: 'Seychelles' },
    { value: 'sl', text: 'Sierra Leone' },
    { value: 'sg', text: 'Singapore' },
    { value: 'sk', text: 'Slovakia' },
    { value: 'si', text: 'Slovenia' },
    { value: 'sb', text: 'Solomon Islands' },
    { value: 'so', text: 'Somalia' },
    { value: 'za', text: 'South Africa' },
    { value: 'kr', text: 'South Korea' },
    { value: 'es', text: 'Spain' },
    { value: 'lk', text: 'Sri Lanka' },
    { value: 'sd', text: 'Sudan' },
    { value: 'sr', text: 'Suriname' },
    { value: 'sj', text: 'Svalbard' },
    { value: 'sz', text: 'Swaziland' },
    { value: 'se', text: 'Sweden' },
    { value: 'ch', text: 'Switzerland' },
    { value: 'sy', text: 'Syria' },
    { value: 'tw', text: 'Taiwan' },
    { value: 'tj', text: 'Tajikistan' },
    { value: 'tz', text: 'Tanzania' },
    { value: 'th', text: 'Thailand' },
    { value: 'tl', text: 'Timorleste' },
    { value: 'tg', text: 'Togo' },
    { value: 'tk', text: 'Tokelau' },
    { value: 'to', text: 'Tonga' },
    { value: 'tt', text: 'Trinidad' },
    { value: 'tn', text: 'Tunisia' },
    { value: 'tr', text: 'Turkey' },
    { value: 'tm', text: 'Turkmenistan' },
    { value: 'tv', text: 'Tuvalu' },
    { value: 'ug', text: 'Uganda' },
    { value: 'ua', text: 'Ukraine' },
    { value: 'ae', text: 'United Arab Emirates' },
    { value: 'us', text: 'United States' },
    { value: 'uy', text: 'Uruguay' },
    { value: 'um', text: 'Us Minor Islands' },
    { value: 'vi', text: 'Us Virgin Islands' },
    { value: 'uz', text: 'Uzbekistan' },
    { value: 'vu', text: 'Vanuatu' },
    { value: 'va', text: 'Vatican City' },
    { value: 've', text: 'Venezuela' },
    { value: 'vn', text: 'Vietnam' },
    { value: 'wf', text: 'Wallis and Futuna' },
    { value: 'eh', text: 'Western Sahara' },
    { value: 'ye', text: 'Yemen' },
    { value: 'zm', text: 'Zambia' },
    { value: 'zw', text: 'Zimbabwe' }
  ]

  public code1 = `<m-dropdown placeholder="Gender" [(value)]="value1">
  <m-dropdown-item [value]="1">Male</m-dropdown-item>
  <m-dropdown-item [value]="0">Female</m-dropdown-item>
</m-dropdown>`;

}
